### PR TITLE
Year labels in network visualiazion

### PR DESCRIPTION
**Pull request by cedrickrause**
[DRAFT]

Initial functionality of placing year labels in network visualization.
- Only %5 years
- Placed slightly above nodes

### CODE REVIEW

**Comment by fabian-beck** [comment]
Generally, works well and is very helpful! Every 5th year is sufficient to display as a label.

If height of network vis is small, labels quickly overlap with nodes 
grafik

-> try to prevent, but probably hard to guarantee
-> place labels in a background layer "behind" the nodes
-> maybe use gray font so that the labels do not visually compete/interfere with the scores?

**Comment by cedrickrause** [comment]
Current look:
grafik

**Comment by cedrickrause** [comment]
Current look:
grafik

**Comment by cedrickrause** [comment]
Merged into v0.2 branch with fe7e3ca076ec6fd84f2098360bf1fef118800a67.
Closing this Pull request.

**Pull request closed without merging**
